# Generated by Django 4.0 on 2025-06-12 20:36

from django.db import migrations
import sample_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="csv_tags",
            field=sample_app.models.CharFieldWithCustomDiff(
                blank=True, max_length=500
            ),
        ),
        migrations.AddField(
            model_name="bookversion",
            name="csv_tags",
            field=sample_app.models.CharFieldWithCustomDiff(
                blank=True, max_length=500
            ),
        ),
    ]
